# Generated by Django 4.0.4 on 2022-05-16 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
